# Generated by Django 5.2 on 2025-04-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default='Unknown'),
        ),
    ]
